### ISSUE TITLE
RTIDDSConnector_new_from_participant

### ISSUE THREAD

**Issue by metarsit** [rticommunity/rticonnextdds-connector-go#9]
@kyoungho I do not know what is the best way to keep in touch with you on the feature request and the medium to ask you question. For now, I will raise an issue to do that. If you can provide me a mean for me to talk to you, that would be great.

Also, I am working on `RTIDDSConnector_new_from_participant` function. I am working on this [branch](https://github.com/metarsit/rticonnextdds-connector-go/tree/feature/Connector-Participant). 

I am curious what does `RTIDDSConnector_new_from_participant` function do exactly? Is it to create a connector from just participant and name? so that I won't need to have to read XML file?

**Comment by kyoungho** [comment]
@metarsit I just created the template for the feature request. If you have any questions about DDS and Connector, please use our community portal (https://community.rti.com) or email me. 

```RTIDDSConnector_new_from_participant``` allows creating a connector from existing participants (DDS participants in C objects) instead of participants defined in XML. We don't want to expose the function in Go Connector because we do not provide a way to create a participant other than the ```NewConnector``` function with XML. Do you have any use case requiring the ```RTIDDSConnector_new_from_participant``` function?

**Comment by metarsit** [comment]
Alrite, let's keep in touch in the email then :)

I am aware that the only way defines participants is through XML `file`. I was hoping we can at least take in XML struct or string. So that we don't have to have 2 file (1 executable and 1 xml file) to make the DDS starts. 

Ideally, if we can just do like `dds.NewConnector(participant interface{}, name string, subpub SUBPUB)` would be nice.. 😆

**Comment by kyoungho** [comment]
@metarsit sure! 

Yes, that will be useful. There would be already a possible way to pass an XML string as a parameter to create a connector. Let me test and get back to you.

**Comment by kyoungho** [comment]
@metarsit I tested with XML strings, and it works. I created the following example. 

https://github.com/rticommunity/rticonnextdds-connector-go/blob/master/examples/writer_xml_string/writer.go

https://github.com/rticommunity/rticonnextdds-connector-go/blob/master/examples/reader_xml_string/reader.go

**Comment by metarsit** [comment]
Perfect! I did not have chance to play with it so did not try it yet :) 

Thanks @kyoungho
